### PR TITLE
modify regex to support input of negative numbers to number component

### PR DESCRIPTION
**Pull request by jamesstaub**
adds support for negative number input

### CODE REVIEW

**Comment by jamesstaub** [comment]
It seems to work fine when linked to a dial. If the dial's range is in the positive range, entering a negative in the number box will default to the lowest number in the dials range. If the dial is set with a negative minimum value, values in that range can be entered in the number box.

I'm not sure when those other math methods are called, but at a glance they look like they should support negative values just fine. 

I modified the codepen from the docs to demonstrate. I was getting Nexus undefined error when trying to import the raw from my github, so I just pasted the minified build into the codepen script editor. 

https://codepen.io/taylorbf/pen/owdpxy

**Comment by mscottnelson** [comment]
This looks good to me! Many thanks for the PR, and thanks for performing the sanity check. I've checked your sanity check and it all checks out and I'm giving this my green check mark. @tatecarson it looks like you are the primary maintainer at the moment. IMHO this is good to merge. 

Since I haven't been active on this project, unless this is time critical for @jamesstaub in some way (is it?), I'll leave merging and revving to you @tatecarson.

**Comment by jamesstaub** [comment]
not super urgent, thanks!

**Comment by tatecarson** [comment]
Sorry this took so long! School just ended.

**Pull request merged**
